use std::collections::HashMap;
use actix_web::{middleware, web, App, HttpServer};


use super::database;
use super::http::handlers;



pub async fn server(ip: String, config_db: HashMap<String, String>) -> std::io::Result<()> {
    log::info!("starting HTTP server at http://{}:8081", &ip);

    let pool = database::create_pool(config_db);

    let server = HttpServer::new(move || {
        App::new()
            // enable logger
            .app_data(web::Data::new(pool.clone()))
            .wrap(middleware::Logger::default())
            // <- limit size of the payload (global configuration)
            .service(web::resource("/signIn").route(web::post().to(handlers::sign_in)))
            .service(web::resource("/signOut").route(web::post().to(handlers::sign_out)))
            .service(web::resource("/account").route(web::post().to(handlers::account)))
            .service(web::resource("/trades").route(web::post().to(handlers::trade)))
            .service(web::resource("/position").route(web::post().to(handlers::positions)))
            .service(web::resource("/net_worth").route(web::post().to(handlers::net_worth)))
            .service(web::resource("/income").route(web::post().to(handlers::incomes)))
            .service(web::resource("/equity").route(web::post().to(handlers::pnl)))
            .service(web::resource("/newPrice").route(web::post().to(handlers::is_price)))
            .service(web::resource("/incomes").route(web::post().to(handlers::history_incomes)))
            .service(web::resource("/open_orders").route(web::post().to(handlers::open_orders)))
            .service(web::resource("/accounts").route(web::post().to(handlers::assets)))
            .service(web::resource("/date_history").route(web::post().to(handlers::date_trade)))
            .service(web::resource("/products").route(web::post().to(handlers::get_products_data)))
            .service(web::resource("/alarm_orders").route(web::post().to(handlers::get_open_orders_data)))
            .service(web::resource("/delect_orders").route(web::post().to(handlers::delect_open_orders_data)))
            .service(web::resource("/add_orders").route(web::post().to(handlers::add_open_orders_data)))
            .service(web::resource("/get_positions").route(web::post().to(handlers::get_positions_data)))
            .service(web::resource("/delect_positions").route(web::post().to(handlers::delect_positions_data)))
            .service(web::resource("/add_positions").route(web::post().to(handlers::add_positions_data)))
            .service(web::resource("/update_positions").route(web::post().to(handlers::update_positions_data)))
            .service(web::resource("/update_ori_balance").route(web::post().to(handlers::update_ori_balance_data)))
            .service(web::resource("/get_accounts").route(web::post().to(handlers::get_account)))
            .service(web::resource("/update_accounts_alarm").route(web::post().to(handlers::update_accounts_alarm)))
            .service(web::resource("/update_threshold").route(web::post().to(handlers::update_positions)))
            .service(web::resource("/update_currency").route(web::post().to(handlers::update_curreny)))
            .service(web::resource("/update_borrow").route(web::post().to(handlers::update_borrow)))
            .service(web::resource("/delete_accounts").route(web::post().to(handlers::delete_accounts_data)))
            .service(web::resource("/add_accounts").route(web::post().to(handlers::add_accounts_data)))
            .service(web::resource("/select_id").route(web::post().to(handlers::select_tra_id)))
            .service(web::resource("/get_net_worths").route(web::post().to(handlers::get_net_worths_data)))
            .service(web::resource("/get_equitys").route(web::post().to(handlers::get_equitys_data)))
            .service(web::resource("/get_single_account").route(web::post().to(handlers::single_account)))
            .service(web::resource("/get_bybit_account").route(web::post().to(handlers::bybit_account)))
            .service(web::resource("/get_bybit_equity").route(web::post().to(handlers::get_bybit_equity)))
            .service(web::resource("/get_bian_equity").route(web::post().to(handlers::get_bian_equity)))
            .service(web::resource("/data_bybit_history").route(web::post().to(handlers::date_bybit_trade)))
            .service(web::resource("/bybit_trades").route(web::post().to(handlers::bybit_trade)))
            .service(web::resource("/bybit_futures_position").route(web::post().to(handlers::futures_bybit_positions)))
            .service(web::resource("/bybit_spot_position").route(web::post().to(handlers::spot_bybit_positions)))
            .service(web::resource("/bybit_futures_open_order").route(web::post().to(handlers::futures_bybit_open_orders)))
            .service(web::resource("/bybit_spot_open_order").route(web::post().to(handlers::spot_bybit_open_orders)))
            .service(web::resource("/bybit_usdc_open_order").route(web::post().to(handlers::spot_bybit_usdc_open_orders)))
            .service(web::resource("/bybit_assets").route(web::post().to(handlers::bybit_assets)))
            .service(web::resource("/bybit_incomes").route(web::post().to(handlers::bybit_incomes)))
            .service(web::resource("/get_bybit_single_account").route(web::post().to(handlers::single_bybit_account)))
            .service(web::resource("/total_bybit_equity").route(web::post().to(handlers::get_total_bybit_equity)))
            .service(web::resource("/total_bian_equity").route(web::post().to(handlers::get_total_bian_equity)))
            .service(web::resource("/clear_equity").route(web::post().to(handlers::clear_equity)))
            .service(web::resource("/get_papi_account").route(web::post().to(handlers::papi_account)))
            .service(web::resource("/get_papi_single_account").route(web::post().to(handlers::single_papi_account)))
            .service(web::resource("/get_papi_positions").route(web::post().to(handlers::papi_positions)))
            .service(web::resource("/get_papi_open_orders").route(web::post().to(handlers::papi_open_orders)))
            .service(web::resource("/get_papi_klines").route(web::post().to(handlers::papi_klines)))
            .service(web::resource("/get_papi_assets").route(web::post().to(handlers::papi_assets)))
            .service(web::resource("/get_papi_incomes").route(web::post().to(handlers::papi_income)))
            .service(web::resource("/get_papi_equity").route(web::post().to(handlers::get_total_papi_bian_equity)))
            .service(web::resource("/get_account_list").route(web::post().to(handlers::account_list)))
            .service(web::resource("/get_account_data").route(web::post().to(handlers::alarm_account_data)))
            .service(web::resource("/insert_trader").route(web::post().to(handlers::insert_trader)))
            .service(web::resource("/insert_account").route(web::post().to(handlers::insert_account)))
            .service(web::resource("/insert_weixin").route(web::post().to(handlers::insert_weixins)))
            .service(web::resource("/get_new_traders").route(web::post().to(handlers::select_new_traders)))
            .service(web::resource("/bybit_new_trades").route(web::post().to(handlers::select_new_bybit_traders)))
            .service(web::resource("/create_invitation").route(web::post().to(handlers::create_invitation)))
            .service(web::resource("/check_invitation").route(web::post().to(handlers::select_invitations)))
            .service(web::resource("/add_accounts_invitation").route(web::post().to(handlers::insert_accounts)))
            .service(web::resource("/select_all_invitation").route(web::post().to(handlers::select_all_invitations)))
            .service(web::resource("/get_trader_notices").route(web::post().to(handlers::get_trader_notices)))
            .service(web::resource("/get_trader_message").route(web::post().to(handlers::get_account_message)))
            .service(web::resource("/add_wx_trader_notices").route(web::post().to(handlers::add_wx_trader_notices)))
            .service(web::resource("/check_wx_ways").route(web::post().to(handlers::check_weixin_ways)))
            .service(web::resource("/check_slack_ways").route(web::post().to(handlers::check_slack_ways)))
            .service(web::resource("/add_slack_trader_notices").route(web::post().to(handlers::add_slack_trader_notices)))
            .service(web::resource("/delete_slack_trader_notices").route(web::post().to(handlers::delete_slack_trader_notices)))
            .service(web::resource("/delete_wx_trader_notices").route(web::post().to(handlers::delete_wx_trader_notices)))
            .service(web::resource("/add_group_name").route(web::post().to(handlers::add_account_group)))
            .service(web::resource("/add_group_tra").route(web::post().to(handlers::add_group_tra)))
            .service(web::resource("/delete_acc_tra").route(web::post().to(handlers::delete_acc_tra)))
            .service(web::resource("/add_acc_group").route(web::post().to(handlers::add_acc_group)))
            .service(web::resource("/get_acc_group_data").route(web::post().to(handlers::get_account_group_data)))
            .service(web::resource("/get_acc_group_data_detail").route(web::post().to(handlers::get_account_detail_group_data)))
            .service(web::resource("/get_acc_group_equitys").route(web::post().to(handlers::get_account_detail_group_equitys)))
            .service(web::resource("/is_acc_group").route(web::post().to(handlers::is_account_group)))
            .service(web::resource("/is_acc_tra").route(web::post().to(handlers::is_account_tra)))
            .service(web::resource("/get_acc_group").route(web::post().to(handlers::get_account_group)))
            .service(web::resource("/get_acc_group_tra").route(web::post().to(handlers::get_account_group_tra)))
    })
    .bind((ip.as_str(), 8081))?
    .run();

    return server.await;
}